export enum ViewState {
  HOME = 'HOME',
  XRAY_FORM = 'XRAY_FORM',
  XRAY_VIEW = 'XRAY_VIEW',
  PRENUP_FORM = 'PRENUP_FORM',
  PRENUP_RESULTS = 'PRENUP_RESULTS',
}

export interface Question {
  id: string;
  category: 'behavior' | 'financial' | 'operations' | 'ethics';
  text: string;
  placeholder: string;
  type: 'text' | 'select';
  options?: string[];
}

export interface XRayProfile {
  sponsorName: string;
  trackRecord: string;
  answers: Record<string, string>;
  createdAt: string;
  verificationData?: {
    verified: boolean;
    confidence: number;
    companyData?: any; // Will be CompanyData from exploriumService
  };
}

export interface PreNupData {
  partnerA: {
    name: string;
    answers: Record<string, string>;
  };
  partnerB: {
    name: string;
    answers: Record<string, string>;
  };
}

export enum AlignmentStatus {
  HIGH = 'HIGH', // Green
  MEDIUM = 'MEDIUM', // Yellow
  LOW = 'LOW', // Red
  PENDING = 'PENDING'
}

export interface AlignmentAnalysis {
  questionId: string;
  status: AlignmentStatus;
  summary: string; // Generated by AI
  score: number; // 0-100
}

export interface AppState {
  currentView: ViewState;
  xRayData: XRayProfile | null;
  preNupData: PreNupData | null;
  analysisResults: AlignmentAnalysis[] | null;
}